name: ooni run
on:
  push:
  schedule:
    - cron: "19 23 3 * *"
jobs:

  unattended:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker build . -t ooniprobe
      - name: Run MTA-STS checks
        run: docker run --volume lists:/lists ooniprobe bash -c "ooniprobe run websites --input-file /lists/mta-sts-list.txt && ooniprobe list"
      - name: Run
        run: docker run ooniprobe bash -c "ooniprobe run unattended && ooniprobe list"

